### ISSUE TITLE
flowtype: ERROR - check_contents Path value is missing for flow_bin_path setting

### ISSUE THREAD

**Issue by Nantris** [Pegase745/sublime-flowtype#12]
I'm not sure what the source of this error is nor do I have any idea how to fix it. Google and Github yield no results. Any ideas?

I have my settings for this plugin in my project settings, under the `settings` key as instructed.
```js
{
	"settings": {
  	    "flow_bin_path": ".\\node_modules\\.bin\\flow",
  	    "check_contents_on_edit": true,
  	    "check_contents_on_save": false
	},
        "folders": {
            // ...my other properties
        }
}
```

**Comment by Nantris** [comment]
Flow is only installed locally, and I've tried both relative and absolute paths to the `flow` and `flow.cmd` files.

**Comment by Pegase745** [comment]
You're under which platform?

**Comment by Nantris** [comment]
Whoops sorry. I'm on Windows 7 x64. Is `check_contents` another key value I need to set somewhere?

**Comment by Nantris** [comment]
I've also tried: `"flow_bin_path": "C:\\projects\\myProject\\node_modules\\flow-bin\\flow-win64-v0.79.1\\flow.exe"`, though I'm not clear if this key is even the source of the issue.

**Comment by Pegase745** [comment]
This should work though: `C:\\projects\\myProject\\node_modules\\.bin\\flow.cmd`
