### ISSUE TITLE
ERROR - type-at-pos Path value is missing for flow_bin_path setting

### ISSUE THREAD

**Issue by devLex1308** [Pegase745/sublime-flowtype#16]
OS: Linux
Flowtype: latest
Path in config is not defined

**Comment by max-mykhailenko** [comment]
@Pegase745 what changes was published also in he last build? Got this error too

**Comment by max-mykhailenko** [comment]
@Pegase745 looks like 1.3.1 fixed this problem

**Comment by max-mykhailenko** [comment]
@devLex1308 please check again

**Comment by Pegase745** [comment]
I am not able to reproduce. Nothing much if you check the changelog, I've just added the `all` option. Nothing related to `type-at-pos`
