### ISSUE TITLE
Does not seem to work on Windows 7

### ISSUE THREAD

**Issue by konoufo** [Pegase745/sublime-flowtype#3]
I have updated the user settings and changed the path to flow : "C:\\...\\node_modules\.bin\flow.cmd" but nothing happens in Sublime 3 when i have this:
```javascript
/* @flow */
function sayHi(toWho: string){
  return 'Hello ' + toWho;
}
sayHi(2)
```

**Comment by Pegase745** [comment]
Could you try and use `\\` as the directory separator of the flow bin path ?
as in `C:\\...\\node_modules.bin\\flow.cmd` maybe

**Comment by konoufo** [comment]
When i wrote `\` , i actually meant `\\`. It started working after i restarted Windows. Thank you very much, it feels so good to use this !
