### ISSUE TITLE
"view type" cut generic type

### ISSUE THREAD

**Issue by p9gehka** [Pegase745/sublime-flowtype#5]
![1c50bc58f3](https://user-images.githubusercontent.com/7669181/30547000-d8242710-9c96-11e7-90b9-4034e7623a87.jpg)
![20295bdd17](https://user-images.githubusercontent.com/7669181/30547012-de9eb4e8-9c96-11e7-83fc-934af0593718.jpg)

sublime.View.show_popup  display Html content and read <Config> like a html tag. maybe solution 
`"stdout['type'].replace('<', '&lt;').replace('>', '&gt;')"`

**Comment by Pegase745** [comment]
Is this the wanted result ?
![subl](https://user-images.githubusercontent.com/1678801/30865891-1a71df76-a2d8-11e7-8ce5-127662d1da71.png)

**Comment by p9gehka** [comment]
yes, thank
