### ISSUE TITLE
Locate and prioritize flow installed through npm (project's node_modules)

### ISSUE THREAD

**Issue by AlexxNica** [Pegase745/sublime-flowtype#7]
# Problem
Not possible to use flow-bin installed locally, automatically.

# Solution
First look for flow installed in `node_modules/` folder; if not present, then proceed to locate and use the globally installed one.

# Use case
Suppose I have a project containing libdefs for an older version of flow, and together with the libdefs I have the proper flow-bin module installed and in my packages.json. If my global flow is newer than the flow version of the project, it'll stop validating accurately and start throwing errors all around.

**Comment by max-mykhailenko** [comment]
How I can manually configure plugin to search flow in `node_modules`?

**Comment by Pegase745** [comment]
I'll make a PR for that.

Le 29 oct. 2017 2:17 PM, "Max Mykhailenko" <notifications@github.com> a
écrit :
