### ISSUE TITLE
Properly search for the correct flow binary (brew/npm/nvm)

### ISSUE THREAD

**Issue by AlexxNica** [Pegase745/sublime-flowtype#8]
# Problem
I use `nvm` to control my Node versions, so my `npm` globally installed modules go directly to nvm's folder, which can be `$HOME/.nvm/versions/node/v8.8.1/bin/flow`, for example. By searching only inside `/usr/local/bin`, the plugin cannot find the flow binary, making me change the settings every time I switch the node version, to get it working.

That's one of the annoying problems I was having with other tools and didn't manage to find any working out of the box.

# Solution
- Try to find and use the same binary used by default on terminal (e.g. `which flow`)
- Use a predefined list of paths that follow a priority order; use the first to be found.

**Comment by Prinzhorn** [comment]
I have flow installed locally in every project like I do with eslint. SublimeLinter finds the local eslint no problem https://github.com/SublimeLinter/SublimeLinter-eslint

The logic can be found here https://github.com/SublimeLinter/SublimeLinter/blob/d1dacc579ae89274ec9733aa9a0e2249ee3d498f/lint/base_linter/node_linter.py

```python
def find_local_cmd_path(self, cmd):
    """
    Find a local binary in node_modules/.bin.
    Given package.json filepath and a local binary to find,
    look in node_modules/.bin for that binary.
    """
    cwd = os.path.dirname(self.manifest_path)

    binary = self.get_pkg_bin_cmd(cmd)

    if binary:
        return os.path.normpath(os.path.join(cwd, binary))

    return self.find_ancestor_cmd_path(cmd, cwd)

def find_ancestor_cmd_path(self, cmd, cwd):
    """Recursively check for command binary in ancestors' node_modules/.bin directories."""
    node_modules_bin = os.path.normpath(os.path.join(cwd, 'node_modules/.bin/'))

    binary = os.path.join(node_modules_bin, cmd)

    if sublime.platform() == 'windows' and os.path.splitext(binary)[1] != '.cmd':
        binary += '.cmd'

    if util.can_exec(binary):
        return binary

    parent = os.path.dirname(cwd)

    if parent == '/' or parent == cwd:
        return None

    return self.find_ancestor_cmd_path(cmd, parent)
```

**Comment by Pegase745** [comment]
Thanks @Prinzhorn , the 1.1.0 release should fix this issue.

Regarding the nvm issue, well it gets complicated as nvm is not a binary so can't seem to find a way to call it in Python with `subprocess`. 
Once it's done, I only need to add to the list of paths to search in, the result of `nvm which current`, so it gives local -> nvm  -> global

**Comment by Prinzhorn** [comment]
@Pegase745 nice, I installed the package and it worked out of the box 👌

**Comment by Pegase745** [comment]
thanks @Prinzhorn for the feedback !
